package com.mytest.mybatisreadwriteway2.model.entity;

import java.util.Date;

public class BizUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.id
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.name
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.age
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.desc
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.create_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.create_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.update_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.update_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.disabled
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private Boolean disabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.phone
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_user.email
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.id
     *
     * @return the value of biz_user.id
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.id
     *
     * @param id the value for biz_user.id
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.name
     *
     * @return the value of biz_user.name
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.name
     *
     * @param name the value for biz_user.name
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.age
     *
     * @return the value of biz_user.age
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.age
     *
     * @param age the value for biz_user.age
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.desc
     *
     * @return the value of biz_user.desc
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.desc
     *
     * @param desc the value for biz_user.desc
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.create_by
     *
     * @return the value of biz_user.create_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.create_by
     *
     * @param createBy the value for biz_user.create_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.create_time
     *
     * @return the value of biz_user.create_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.create_time
     *
     * @param createTime the value for biz_user.create_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.update_by
     *
     * @return the value of biz_user.update_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.update_by
     *
     * @param updateBy the value for biz_user.update_by
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.update_time
     *
     * @return the value of biz_user.update_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.update_time
     *
     * @param updateTime the value for biz_user.update_time
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.disabled
     *
     * @return the value of biz_user.disabled
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.disabled
     *
     * @param disabled the value for biz_user.disabled
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.phone
     *
     * @return the value of biz_user.phone
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.phone
     *
     * @param phone the value for biz_user.phone
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_user.email
     *
     * @return the value of biz_user.email
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_user.email
     *
     * @param email the value for biz_user.email
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }
}