package com.mytest.mybatisreadwriteway3.dao.auto;

import com.mytest.mybatisreadwriteway3.model.entity.BizUser;

public interface BizUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    int insert(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    int insertSelective(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    BizUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    int updateByPrimaryKeySelective(BizUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_user
     *
     * @mbg.generated Thu Mar 12 16:26:31 CST 2020
     */
    int updateByPrimaryKey(BizUser record);
}